image: node:lts-buster

pages:
  script:
    - npm ci
    - cp -R src srcx
    - find ./srcx -name "*.js" -print0 | xargs -0 sed -i "s/@typedef {typeof import/@xtypedef {typeof import/g"
    - npm run docs
    - ls -al -R public
  artifacts:
    paths:
      - public
  only:
    - master
